# Generated by Django 4.0.6 on 2022-09-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_no', models.CharField(max_length=20)),
                ('distance', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('images', models.ImageField(upload_to='')),
                ('area', models.IntegerField()),
                ('no_of_rooms', models.IntegerField()),
                ('price', models.IntegerField()),
                ('property_type', models.CharField(choices=[('hostel', 'HOST'), ('house', 'HOUSE'), ('room', 'ROOM'), ('flat', 'FLAT')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RenterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
