# Generated by Django 4.0.6 on 2022-09-11 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentdetails',
            name='renterInfo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.renterinfo'),
        ),
    ]
